spring.application.name=fintech-ledger

# MySQL DB
spring.datasource.url=jdbc:mysql://localhost:3306/fintech_ledger
spring.datasource.username=root
spring.datasource.password=LQ23+ym#fdG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# IMPORTANT: disable SQL logging (prevents connection reset)
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.orm.jdbc.bind=off

server.port=8080
